---

# Thanks to geerlingguy!

language: python
services: docker

env:
  global:
    - ROLE_NAME: terraform
  matrix:
    # Local user install
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos8
    - MOLECULE_DISTRO: debian10
    - MOLECULE_DISTRO: ubuntu1804
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: amazonlinux2

install:
  # Install test dependencies.
  - pip install -r molecule/requirements.txt

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-terraform-controller xanmanning.$ROLE_NAME
  - cd xanmanning.$ROLE_NAME

script:
  # Run tests.
  - molecule test --all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
