---

- name: Get the version information of the latest release of Terraform
  uri:
    url: https://api.github.com/repos/hashicorp/terraform/releases/latest
    return_content: true
    body_format: json
  register: terraform_get_latest_version

- name: Ensure the terraform_version variable is set
  set_fact:
    terraform_version: "{{ terraform_get_latest_version.json.tag_name | regex_replace('^v', '') }}"
