---

- name: Prepare containers for local-user install testing
  hosts: all
  become: true
  tasks:
    - name: Ensure a user group exists
      group:
        name: user
        state: present

    - name: Ensure a normal user exists
      user:
        name: terraformuser
        group: user
        state: present

    - name: Ensure unzip is installed
      package:
        name: unzip
        state: present
